In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel(r'C:\Users\Tathagat\Documents\University of Delaware\STAT 613 Multivariate Statistics\HW 3\UCI_Credit_Card.xlsx')
df.head() # credit card default data set

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...          0          0          0         0       689         0   
1  ...       3272       3455       3261         0      1000      1000   
2  ...      14331      14948      15549      1518      1500      1000   
3  ...      28314      28959      29547      2000      2019      1200   
4  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  DEFAULT  
0         0         0         0        1  
1      1000         0      2000        1  
2      1000      1000      5000        0  
3      1100      1069      1000        0  
4      9000       689       679        0  

[5 rows x 25 columns]

In [3]:
df.shape

(30000, 25)

In [4]:
X = df.drop(['ID','DEFAULT'],axis=1) # feature matrix excluding unncessary ID variable
y = df['DEFAULT'] # target vector for default status variable

In [5]:
from sklearn.model_selection import train_test_split # training set is 80% and validation set is 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2)

In [6]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
model = LinearDiscriminantAnalysis()
model.fit(X_train,y_train) # fit a Linear Discriminant Analysis model

LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
                           solver='svd', store_covariance=False, tol=0.0001)

In [7]:
train_pred = model.predict(X_train)
train_pred # LDA model predictions for default status using training data set

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [8]:
from sklearn.metrics import confusion_matrix

In [9]:
train_cm = confusion_matrix(y_train,train_pred)
print(train_cm) # confusion matrix of LDA model using training data set

[[18088   562]
 [ 3976  1374]]


In [10]:
test_pred = model.predict(X_test)
test_pred # LDA model predictions for default status using validation data set

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [11]:
test_cm = confusion_matrix(y_test,test_pred)
print(test_cm) # confusion matrix of LDA model using validation data set

[[4553  161]
 [ 958  328]]


In [12]:
train_score = model.score(X_train,y_train)
train_score # LDA model accuracy score using training data set

0.8109166666666666

In [13]:
test_score = model.score(X_test,y_test)
test_score # LDA model accuracy score using validation data set

0.8135

In [14]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
model2 = QuadraticDiscriminantAnalysis()
model2.fit(X_train,y_train) # fit a Quadratic Discriminant Analysis model

QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)

In [15]:
train_pred2 = model2.predict(X_train)
train_pred2 # QDA model predictions for default status using training data set

array([0, 1, 0, ..., 1, 1, 1], dtype=int64)

In [16]:
train_cm2 = confusion_matrix(y_train,train_pred2)
print(train_cm2) # confusion matrix of QDA model using training data set

[[ 8558 10092]
 [ 1028  4322]]


In [17]:
test_pred2 = model2.predict(X_test)
test_pred2 # QDA model predictions for default status using validation data set

array([0, 0, 1, ..., 0, 1, 0], dtype=int64)

In [18]:
test_cm2 = confusion_matrix(y_test,test_pred2)
print(test_cm2) # confusion matrix of QDA model using validation data set

[[2091 2623]
 [ 244 1042]]


In [19]:
train_score2 = model2.score(X_train,y_train)
train_score2 # QDA model accuracy score using training data set

0.5366666666666666

In [20]:
test_score2 = model2.score(X_test,y_test)
test_score2 # QDA model accuracy score using validation data set

0.5221666666666667

In [21]:
# Based on these results, Linear Discrminant Analysis is better than Quadratic Discriminant Analysis
# for discriminating between default cases and non-default cases